apiVersion: apps/v1
kind: Deployment
metadata:
    name: zipkin
    labels:
        app: zipkin
spec:
    replicas: 1
    selector:
        matchLabels:
            app: zipkin
    minReadySeconds: 10
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        type: RollingUpdate
    template:
        metadata:
            name: zipkin
            labels:
                app: zipkin
        spec:
            containers:
            - name: zipkin
              image: openzipkin/zipkin
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
spec:
  type: ClusterIP
  selector:
    app: zipkin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9411
---    
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service-public
spec:
  type: LoadBalancer
  selector:
    app: zipkin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9411

