apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-discovery
    labels:
        app: service-discovery
spec:
    replicas: 1
    selector:
        matchLabels:
            app: service-discovery
    minReadySeconds: 10
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        type: RollingUpdate
    template:
        metadata:
            name: service-discovery
            labels:
                app: service-discovery
        spec:
            containers:
            - name: service-discovery
              image: nikolahristovski/service_registry:0.0.1-SNAPSHOT
              ports:
              - containerPort: 8761     
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery-priv-service
spec:
  type: ClusterIP
  selector:
    app: service-discovery
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8761
