apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-product-config
  labels:
    app: postgres-product
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-product-pv-claim
  labels:
    app: postgres-product
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-product
  labels:
        app: postgres-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product
  template:
    metadata:
      name: postgres-product
      labels:
        app: postgres-product
    spec:
      containers:
        - name: postgres-product
          image: postgres
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-product-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
              subPath: postgres
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-product-pv-claim
---            
apiVersion: v1
kind: Service
metadata:
  name: postgres-product-service
spec:
  type: ClusterIP
  selector:
    app: postgres-product
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---      
apiVersion: apps/v1
kind: Deployment
metadata:
    name: product
    labels:
        app: product
spec:
    replicas: 3
    selector:
        matchLabels:
            app: product
    minReadySeconds: 10
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        type: RollingUpdate
    template:
        metadata:
            name: product
            labels:
                app: product
        spec:
            containers:
            - name: product
              image: nikolahristovski/product:0.0.1-SNAPSHOT
              ports:
              - containerPort: 8200
              imagePullPolicy: Always
            initContainers:  
            - name: init-service-discovery
              image: busybox:1.28
              command: ['sh', '-c', "until nslookup service-discovery-priv-service.default.svc.cluster.local; do echo waiting for service-discovery-priv-service.default.svc.cluster.local; sleep 2; done"]  
            - name: init-zipkin
              image: busybox:1.28
              command: ['sh', '-c', "until nslookup zipkin-service.default.svc.cluster.local; do echo waiting for zipkin-service.default.svc.cluster.local; sleep 2; done"]              
            - name: init-config-server
              image: busybox:1.28
              command: ['sh', '-c', "until nslookup config-server-service.default.svc.cluster.local; do echo waiting for config-server-service.default.svc.cluster.local; sleep 2; done"]                              
            - name: init-db
              image: busybox:1.28
              command: ['sh', '-c', "until nslookup postgres-product-service.default.svc.cluster.local; do echo waiting for postgres-product-service.default.svc.cluster.local; sleep 2; done"]                                
            - name: init-kafka
              image: busybox:1.28
              command: ['sh', '-c', "until nslookup my-cluster-kafka-bootstrap.kafka.svc.cluster.local; do echo waiting for my-cluster-kafka-bootstrap.kafka.svc.cluster.local; sleep 2; done"]                   
---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8200
