apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-user-config
  labels:
    app: postgres-user
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-user-pv-claim
  labels:
    app: postgres-user
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user
  labels:
        app: postgres-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      name: postgres-user
      labels:
        app: postgres-user
    spec:
      containers:
        - name: postgres-user
          image: postgres
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-user-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
              subPath: postgres
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-user-pv-claim
---            
apiVersion: v1
kind: Service
metadata:
  name: postgres-user-service
spec:
  type: ClusterIP
  selector:
    app: postgres-user
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: user
    labels:
        app: user
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user
    minReadySeconds: 10
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        type: RollingUpdate
    template:
        metadata:
            name: user
            labels:
                app: user
        spec:
            containers:
            - name: user
              image: nikolahristovski/user:0.0.1-SNAPSHOT
              ports:
              - containerPort: 8080
              imagePullPolicy: Always  
            initContainers:  
            - name: init-service-discovery
              image: busybox:1.28
              command: ['sh', '-c', "until nslookup service-discovery-priv-service.default.svc.cluster.local; do echo waiting for service-discovery-priv-service.default.svc.cluster.local; sleep 2; done"]  
            - name: init-zipkin
              image: busybox:1.28
              command: ['sh', '-c', "until nslookup zipkin-service.default.svc.cluster.local; do echo waiting for zipkin-service.default.svc.cluster.local; sleep 2; done"]              
            - name: init-config-server
              image: busybox:1.28
              command: ['sh', '-c', "until nslookup config-server-service.default.svc.cluster.local; do echo waiting for config-server-service.default.svc.cluster.local; sleep 2; done"]                              
            - name: init-db
              image: busybox:1.28
              command: ['sh', '-c', "until nslookup postgres-user-service.default.svc.cluster.local; do echo waiting for postgres-user-service.default.svc.cluster.local; sleep 2; done"]  
            - name: init-kafka
              image: busybox:1.28
              command: ['sh', '-c', "until nslookup my-cluster-kafka-bootstrap.kafka.svc.cluster.local; do echo waiting for my-cluster-kafka-bootstrap.kafka.svc.cluster.local; sleep 2; done"]                   
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

