apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    minReadySeconds: 10
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        type: RollingUpdate
    template:
        metadata:
            name: frontend
            labels:
                app: frontend
        spec:
            containers:
            - name: frontend
              image: nikolahristovski/frontend:0.0.1
              ports:
              - containerPort: 80
              imagePullPolicy: Always  
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80          
